# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
