# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helper.models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
