# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likehospital',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_liked', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='likehospital',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_liked', to='helper.Hospital'),
        ),
    ]
