# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(0, b'started'), (3, b'submitted'), (2, b'translating_origin'), (4, b'return'), (5, b'translating_feedback'), (6, b'feedback'), (1, b'PAID')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='week_number_at_submit',
            field=models.IntegerField(default=-1),
        ),
    ]
