# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latest_upload',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderpatient',
            name='relationship',
            field=models.CharField(choices=[('SELF', 'SELF'), ('RELATIVE', 'RELATIVE'), ('CLIENT', 'CLIENT')], default='SELF', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 16, 13, 50, 815000, tzinfo=utc)),
        ),
    ]
