# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 3, 58, 19, 717528, tzinfo=utc)),
        ),
    ]
