# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AddField(
            model_name='staff',
            name='sequence',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
