# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreview',
            name='review_number',
            field=models.IntegerField(default=0),
        ),
    ]
