# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(default=10000)),
                ('full_price', models.IntegerField(default=100000)),
                ('disease', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disease_price', to='helper.Disease')),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slots', models.IntegerField(default=20)),
                ('slots_open_0', models.IntegerField(default=20)),
                ('slots_open_1', models.IntegerField(default=20)),
                ('slots_open_2', models.IntegerField(default=20)),
                ('slots_open_3', models.IntegerField(default=20)),
                ('disease', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disease_slot', to='helper.Disease')),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deposit_paid',
        ),
        migrations.AddField(
            model_name='slot',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_slot', to='helper.Hospital'),
        ),
        migrations.AddField(
            model_name='price',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_price', to='helper.Hospital'),
        ),
    ]
