# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disease',
            table='disease',
        ),
        migrations.AlterModelTable(
            name='hospital',
            table='hospital',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='rank',
            table='rank',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
