# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpatient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
