# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 03:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import info.utility


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.FileField(null=True, upload_to=info.utility.questions_path)),
                ('disease', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helper.Disease')),
                ('hospital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helper.Hospital')),
            ],
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='deposite',
            new_name='deposit',
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 2, 3, 46, 32, 710000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='trans_status',
            field=models.CharField(choices=[(0, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe6\x9c\xaa\xe5\xbc\x80\xe5\xa7\x8b'), (1, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe8\xbf\x9b\xe8\xa1\x8c\xe4\xb8\xad'), (2, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad'), (4, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe5\xb7\xb2\xe5\xae\xa1\xe6\xa0\xb8'), (3, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe9\xa9\xb3\xe5\x9b\x9e'), (5, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90'), (6, b'\xe8\x8b\xb1\xe8\xaf\x91\xe6\xb1\x89\xe6\x9c\xaa\xe5\xbc\x80\xe5\xa7\x8b'), (7, b'\xe8\x8b\xb1\xe8\xaf\x91\xe6\xb1\x89\xe8\xbf\x9b\xe8\xa1\x8c\xe4\xb8\xad'), (8, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad'), (9, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe5\xb7\xb2\xe5\xae\xa1\xe6\xa0\xb8'), (10, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe9\xa9\xb3\xe5\x9b\x9e'), (11, b'\xe6\xb1\x89\xe8\xaf\x91\xe8\x8b\xb1\xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90'), (12, b'\xe8\xae\xa2\xe5\x8d\x95\xe5\xae\x8c\xe6\x88\x90')], default=0, max_length=20),
        ),
    ]
