# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likehospital',
            name='customer',
        ),
        migrations.AddField(
            model_name='likehospital',
            name='customer',
            field=models.ManyToManyField(to='customer.Customer'),
        ),
        migrations.RemoveField(
            model_name='likehospital',
            name='hospital',
        ),
        migrations.AddField(
            model_name='likehospital',
            name='hospital',
            field=models.ManyToManyField(to='helper.Hospital'),
        ),
    ]
