# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='slots_open',
            new_name='slots_open_0',
        ),
        migrations.AddField(
            model_name='hospital',
            name='default_slots',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_1',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_2',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_3',
            field=models.IntegerField(default=20),
        ),
    ]
