# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_trans',
            new_name='extra_document',
        ),
    ]
