# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170808_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 13, 13, 32, 29, 903733, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='rank',
            name='disease',
        ),
        migrations.AddField(
            model_name='rank',
            name='disease',
            field=models.ManyToManyField(to='helper.Disease'),
        ),
        migrations.RemoveField(
            model_name='rank',
            name='hospital',
        ),
        migrations.AddField(
            model_name='rank',
            name='hospital',
            field=models.ManyToManyField(to='helper.Hospital'),
        ),
    ]
