# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170912_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpatient',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth',
        ),
    ]
