# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170930_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='document_complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_payment_paid',
        ),
    ]
