# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20171001_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
