# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170718_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='likehospital',
            name='disease',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disease_liked', to='helper.Disease'),
        ),
    ]
