# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170827_2256'),
        ('helper', '0002_auto_20170829_1024'),
    ]

    operations = [
    ]
