# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('helper', '0002_auto_20170717_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likehospital',
            name='customer',
        ),
        migrations.AddField(
            model_name='likehospital',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.RemoveField(
            model_name='likehospital',
            name='hospital',
        ),
        migrations.AddField(
            model_name='likehospital',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='helper.Hospital'),
        ),
    ]
