# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_price_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deposit_paid',
        ),
    ]
