# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 02:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170807_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 2, 48, 35, 248334, tzinfo=utc)),
        ),
    ]
