# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import helper.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20170521_1105'),
        ('helper', '0002_auto_20170401_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_1', models.PositiveSmallIntegerField(default=0)),
                ('week_2', models.PositiveSmallIntegerField(default=0)),
                ('week_3', models.PositiveSmallIntegerField(default=0)),
                ('week_4', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_not_trans', models.FileField(blank=True, upload_to=helper.models.order_directory_path)),
                ('case_trans', models.FileField(blank=True, upload_to=helper.models.order_directory_path)),
                ('feedback_not_trans', models.FileField(blank=True, upload_to=helper.models.order_directory_path)),
                ('feedback_trans', models.FileField(blank=True, upload_to=helper.models.order_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OTHER', 'Other')], default='M', max_length=5)),
                ('catagory', models.CharField(choices=[('CANCER', 'Cancer'), ('COLD', 'Cold')], default='COLD', max_length=50)),
                ('diagnose_hospital', models.TextField(blank=True)),
                ('doctor', models.TextField(blank=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='capacity',
        ),
        migrations.AddField(
            model_name='hospital',
            name='feedback_time',
            field=models.CharField(default='one week', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='price_range',
            field=models.CharField(default='unkown', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialty',
            field=models.TextField(default='specialty'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimate_feedback',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'started'), (1, 'submitted'), (2, 'recieved'), (3, 'feedback'), (4, 'paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.CharField(default='unkown', max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='keyword',
            field=models.CharField(default='unkown', max_length=150),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='introduction',
            field=models.TextField(default='intro'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='document',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Order'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Hospital'),
        ),
        migrations.AddField(
            model_name='order',
            name='document_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helper.Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='helper.Patient'),
            preserve_default=False,
        ),
    ]
