# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_order_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='step',
            field=models.IntegerField(null=True),
        ),
    ]
