# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170703_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='week_number_at_submit',
            field=models.IntegerField(default=0),
        ),
    ]
