# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_hospitalreview_review_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalreview',
            name='review_number',
        ),
    ]
