# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_auto_20170821_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 14, 25, 6, 549884, tzinfo=utc)),
        ),
    ]
