# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20171226_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receive',
        ),
        migrations.AlterField(
            model_name='order',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
