# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20170813_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 13, 14, 53, 49, 629209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rank',
            name='disease',
            field=models.ManyToManyField(default=None, related_name='disease_rank', to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='hospital',
            field=models.ManyToManyField(default=None, related_name='hospital_rank', to='helper.Hospital'),
        ),
    ]
