# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_likehospital_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.tzinfo),
        ),
    ]
