# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20170523_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='document',
            name='order_id',
        ),
    ]
