# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20170912_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpatient',
            name='birth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
