# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helper.models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_merge_20170829_1554'),
    ]

    operations = [

        migrations.AddField(
            model_name='document',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),

    ]
