# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20170930_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='document_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='full_payment_paid',
            field=models.BooleanField(default=False),
        ),
    ]
