# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20170712_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
