# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_order_week_number_at_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='week_number_at_submit',
        ),
    ]
