# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20170826_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latest_upload',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 4, 1, 45, 528681, tzinfo=utc)),
        ),
    ]
