# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('helper', '0004_order_auto_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ManyToManyField(to='customer.Customer')),
                ('hospital', models.ManyToManyField(to='helper.Hospital')),
            ],
            options={
                'db_table': 'customer_like_hospital',
            },
        ),
    ]
