# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_remove_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='category',
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnose_hospital',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
