# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_auto_20171226_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Order'),
        ),
        migrations.AlterField(
            model_name='hospitalreview',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_review', to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalreview',
            name='order',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_review', to='helper.Order'),
        ),
        migrations.AlterField(
            model_name='likehospital',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_liked', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='likehospital',
            name='disease',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_liked', to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='likehospital',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_liked', to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_C2E',
            field=models.ForeignKey(null=True, on_delete=models.SET(1), related_name='chinese_translator', to='helper.Staff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_E2C',
            field=models.ForeignKey(null=True, on_delete=models.SET(1), related_name='english_translator', to='helper.Staff'),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='birth',
            field=models.DateField(default=None, null=True, verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='contact',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='diagnose_hospital',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='doctor',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='first_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='passport',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='pin_yin',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnose_hospital',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pin_yin',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='disease',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_price', to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='price',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_price', to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='disease',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='disease',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_rank', to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_rank', to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='disease',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_slot', to='helper.Disease'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='hospital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_slot', to='helper.Hospital'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
