# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_auto_20170930_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='deposite',
        ),
    ]
