# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_order_deposit_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'get_latest_by': 'sequence'},
        )
    ]
