# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_remove_order_week_number_at_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='week_number_at_submit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_C2E',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chinese_translator', to='translator.Translator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='translator_E2C',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='english_translator', to='translator.Translator'),
        ),
    ]
