# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_remove_order_document_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_complete',
            field=models.BooleanField(default=False),
        ),
    ]
