# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helper.models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_auto_20170523_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='case_not_trans',
        ),
        migrations.RemoveField(
            model_name='document',
            name='case_trans',
        ),
        migrations.RemoveField(
            model_name='document',
            name='feedback_not_trans',
        ),
        migrations.RemoveField(
            model_name='document',
            name='feedback_trans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=helper.models.order_directory_path),
        ),
        migrations.AddField(
            model_name='document',
            name='document_trans',
            field=models.FileField(null=True, upload_to=helper.models.order_directory_path),
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.Order'),
        ),
        migrations.AddField(
            model_name='document',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='overall_rank',
            field=models.IntegerField(default=0),
        ),
    ]
