# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_auto_20170829_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='average_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='review_number',
            field=models.IntegerField(default=0),
        ),
    ]
