# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170607_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_trans',
            new_name='extra_document',
        ),
    ]
