# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170802_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 2, 27, 26, 523000, tzinfo=utc)),
        ),
    ]
