# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170813_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 13, 14, 56, 25, 125524, tzinfo=utc)),
        ),
    ]
