# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_remove_rank_deposite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='deposit',
            field=models.IntegerField(default=10000),
        ),
    ]
