# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:10
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170918_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trans_status',
            field=models.CharField(choices=[(0, b'c2e_not_started'), (1, b'c2e_ongoing'), (2, b'c2e_approving'), (4, b'c2e_approved'), (3, b'c2e_disapproved'), (5, b'c2e_finished'), (6, b'c2e_not_started'), (7, b'c2e_ongoing'), (8, b'c2e_approving'), (9, b'c2e_approved'), (10, b'c2e_disapproved'), (11, b'c2e_finished'), (12, b'all_finished')], default=0, max_length=20),
        ),
    ]
