# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170718_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likehospital',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_customer', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='likehospital',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_hospital', to='helper.Hospital'),
        ),
    ]
