# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_order_document_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='default_slots',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_0',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_1',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_2',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slots_open_3',
            field=models.IntegerField(default=20),
        ),
    ]
