# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170803_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 22, 36, 58, 680858, tzinfo=utc)),
        ),
    ]
