# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20170829_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_feedback',
        ),
    ]
