# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20171006_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='default_slots',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='slots_open_0',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='slots_open_1',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='slots_open_2',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='slots_open_3',
        ),
    ]
