# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_remove_document_is_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
