# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20170821_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpatient',
            name='relationship',
            field=models.CharField(choices=[('SELF', 'SELF'), ('RELATIVE', 'RELATIVE'), ('CLIENT', 'CLIENT')], default='SELF', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 14, 26, 53, 980954, tzinfo=utc)),
        ),
    ]
