# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_rank_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='full_price',
        ),
    ]
