# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import helper.models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20170919_2210'),
    ]

    operations = [

        migrations.AddField(
            model_name='staff',
            name='sequence',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 2, 42, 59, 907000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=helper.models.order_directory_path),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='review_number',
            field=models.IntegerField(blank=True),
        ),
    ]
