# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20170716_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likehospital',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='LikeHospital',
        ),
    ]
