# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20170826_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review_number', models.IntegerField()),
                ('hospital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_review', to='helper.Hospital')),
            ],
            options={
                'db_table': 'hospital_review',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 5, 21, 15, 839636, tzinfo=utc)),
        ),
    ]
