# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_auto_20170919_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sequence',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
