# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_remove_rank_full_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='full_price',
            field=models.IntegerField(default=100000),
        ),
    ]
