# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_document_is_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpatient',
            name='passport',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
