# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_auto_20170727_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
