# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_auto_20171006_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='default_slots',
        ),
    ]
