# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_auto_20170716_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
