# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_like_hospitals'),
        ('helper', '0008_auto_20170716_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helper.Hospital')),
            ],
            options={
                'db_table': 'like_hospital',
            },
        ),
    ]
