# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20170919_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_payment_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='default_slots',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_0',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_1',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_2',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_3',
            field=models.IntegerField(default=20),
        ),
    ]
