# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20170901_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='step',
        ),
    ]
