# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20170919_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='sequence',
        ),
        migrations.AddField(
            model_name='order',
            name='full_payment_paid',
            field=models.BooleanField(default=False),
        ),
    ]
