# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20170727_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=b'<function now at 0x10cfd4e60>'),
        ),
    ]
