# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_auto_20170921_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
