# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_auto_20170930_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='default_slots',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='deposit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='rank',
            name='full_price',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_0',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_1',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_2',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='slots_open_3',
            field=models.IntegerField(default=20),
        ),
    ]
