# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_remove_order_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpatient',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='diagnose_hospital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='doctor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpatient',
            name='passport',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnose_hospital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(default='', max_length=50),
        ),
    ]
