# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_likehospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likehospital',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='likehospital',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Hospital'),
        ),
    ]
