# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20170930_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='full_price',
        ),
    ]
