# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20170904_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_yin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
