# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20170921_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='feedback_time',
            field=models.IntegerField(default=1),
        ),
    ]
