# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 01:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20170716_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'started'), (4, 'submitted'), (3, 'translating_origin'), (2, 'received'), (5, 'return'), (6, 'translating_feedback'), (7, 'feedback'), (1, 'PAID')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 21, 48, 37, 838000)),
        ),
    ]
