# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_auto_20170910_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpatient',
            name='birth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
