# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_auto_20170910_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pin_yin',
        ),
    ]
