# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_auto_20170930_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='deposit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='rank',
            name='full_price',
            field=models.IntegerField(default=100000),
        ),
    ]
