# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_auto_20170930_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='default_slots',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='full_price',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='slots_open_0',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='slots_open_1',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='slots_open_2',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='slots_open_3',
        ),
    ]
