# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_remove_patient_pin_yin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pin_yin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
