# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_auto_20170911_0951'),
        ('helper', '0013_patient_pin_yin'),
    ]

    operations = [
    ]
