# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_auto_20170912_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpatient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orderpatient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='orderpatient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderpatient',
            name='pin_yin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pin_yin',
        ),
    ]
