# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0003_remove_hospitalreview_review_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(default=None, max_length=150)),
                ('disease', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form_disease', to='helper.Disease')),
                ('hospital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form_hospital', to='helper.Hospital')),
            ],
            options={
                'db_table': 'dynamic_form',
            },
        ),
    ]
