# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170322_0407'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='auth_customer',
        ),
    ]
