# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_like_hospitals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='like_hospitals',
            field=models.ManyToManyField(to='helper.Hospital'),
        ),
    ]
