# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170322_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
