# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170716_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='like_hospitals',
        ),
    ]
