# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170324_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=b'unknown'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.TextField(default=b'unknown'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.TextField(default=b'unknown'),
        ),
    ]
