# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translator',
            name='assignments',
            field=models.ManyToManyField(to='helper.Order'),
        ),
    ]
