# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_auto_20170622_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='active',
        ),
    ]
